version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: laravel-mysql
        restart: unless-stopped
        ports:
            - "3308:3306"
        environment:
            MMYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel-phpmyadmin
        restart: unless-stopped
        ports:
            - "8082:80"
        depends_on:
            - db
        networks:
            - laravel

volumes:
    dbdata:

networks:
    laravel:
